import { randomBytes } from "node:crypto";
import { readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

export type ReporterStrategy = "config_wrapper" | "cli_override";

export interface PreparedRunConfig {
  strategy: ReporterStrategy;
  /** Extra CLI arguments that select the reporter/config for this run. */
  args: string[];
  /** Environment overrides for the runner process. */
  env: Record<string, string>;
  wrapperPath?: string;
  /** Why the wrapper could not be used, when strategy is cli_override. */
  fallbackReason?: string;
  cleanup: () => void;
}

const activeWrappers = new Set<string>();

function removeWrapper(wrapperPath: string): void {
  activeWrappers.delete(wrapperPath);
  try {
    rmSync(wrapperPath, { force: true });
  } catch {
    // Best-effort cleanup; the file name marks it as generated and safe to delete.
  }
}

const WRAPPER_NAME_RE = /^\.pw-mcp-(\d+)-[0-9a-f]{8}\.config\.ts$/;

function processIsAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    // EPERM means the process exists but belongs to another user.
    return (error as NodeJS.ErrnoException).code === "EPERM";
  }
}

/** Delete wrappers left behind by a server that was killed (e.g. SIGKILL) before it could clean up. */
export function removeStaleWrappers(configDirectory: string): string[] {
  const removed: string[] = [];
  let entries: string[];
  try {
    entries = readdirSync(configDirectory);
  } catch {
    return removed;
  }
  for (const entry of entries) {
    const match = entry.match(WRAPPER_NAME_RE);
    if (!match) continue;
    const pid = Number(match[1]);
    if (pid === process.pid || processIsAlive(pid)) continue;
    const stalePath = path.join(configDirectory, entry);
    try {
      rmSync(stalePath, { force: true });
      removed.push(stalePath);
    } catch {
      // Leave it; the next run will try again.
    }
  }
  return removed;
}

/** Remove wrappers of runs that are still in flight. Synchronous for use in exit handlers. */
export function cleanupRunConfigs(): void {
  for (const wrapperPath of [...activeWrappers]) removeWrapper(wrapperPath);
}

export function wrapperConfigSource(userConfigFileName: string): string {
  return [
    "// Generated by playwright-generate-mcp for a single test run. Safe to delete.",
    "// It loads the project config unchanged and appends a JSON reporter so the project's own",
    "// reporters (HTML, Allure, …) keep working while the MCP server reads structured results.",
    `import userConfigModule from ${JSON.stringify(`./${userConfigFileName}`)};`,
    "const userConfig: any = (userConfigModule as any)?.default ?? userConfigModule;",
    "const configured = userConfig.reporter;",
    "const reporters: any[] = configured === undefined ? [] : typeof configured === 'string' ? [[configured]] : [...configured];",
    "export default { ...userConfig, reporter: [...reporters, ['json', { outputFile: process.env.PW_MCP_JSON_OUTPUT }]] };",
    "",
  ].join("\n");
}

/**
 * Choose how the runner obtains a JSON report.
 *
 * With a project config, a temporary wrapper config is written next to it (so relative paths such
 * as testDir resolve identically) that appends the JSON reporter to the project's reporters.
 * `--reporter=json` is only used when there is no config or the wrapper cannot be written, because
 * that flag replaces every reporter configured by the project.
 */
export function prepareRunConfig(options: { configPath?: string; jsonReportPath: string }): PreparedRunConfig {
  // The HTML reporter otherwise serves the report and blocks until the user closes it.
  const baseEnv = { PW_TEST_HTML_REPORT_OPEN: "never" };
  const cliOverride = (fallbackReason?: string): PreparedRunConfig => ({
    strategy: "cli_override",
    args: ["--reporter=json"],
    env: { ...baseEnv, PLAYWRIGHT_JSON_OUTPUT_NAME: options.jsonReportPath },
    ...(fallbackReason ? { fallbackReason } : {}),
    cleanup: () => undefined,
  });

  if (!options.configPath) return cliOverride();

  const configDirectory = path.dirname(options.configPath);
  removeStaleWrappers(configDirectory);
  const wrapperPath = path.join(configDirectory, `.pw-mcp-${process.pid}-${randomBytes(4).toString("hex")}.config.ts`);
  try {
    writeFileSync(wrapperPath, wrapperConfigSource(path.basename(options.configPath)), { encoding: "utf8", flag: "wx" });
  } catch (error) {
    return cliOverride(`Could not write the temporary wrapper config: ${error instanceof Error ? error.message : String(error)}`);
  }
  activeWrappers.add(wrapperPath);
  return {
    strategy: "config_wrapper",
    args: ["--config", wrapperPath],
    env: { ...baseEnv, PW_MCP_JSON_OUTPUT: options.jsonReportPath },
    wrapperPath,
    cleanup: () => removeWrapper(wrapperPath),
  };
}
